server:
  port: 8080

spring:
  application:
    name: wallet-service

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
#    url: ${POSTGRES_DB_URL:jdbc:postgresql://wallet_database:5432/wallet}
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/wallet}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  token:
    secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    expired: 3600000
